---
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - prettier
  - import
extends:
  - prettier
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
env:
  node: true
rules:
  no-underscore-dangle: 0
  no-template-curly-in-string: 0
  prettier/prettier:
    - "error"
    - parser: "babel"
      printWidth: 200
      semi: false
      singleQuote: true
      endOfline: "lf"
      trailingComma: "none"
globals:
  proto: readonly
